import { prisma } from "./db.ts";

async function main() {
    await prisma.market.createMany({
        data: [
            // majors vs USDT
            {
                pair: "BTC/USDT",
                baseAsset: "BTC",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "ETH/USDT",
                baseAsset: "ETH",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "SOL/USDT",
                baseAsset: "SOL",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "BNB/USDT",
                baseAsset: "BNB",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "XRP/USDT",
                baseAsset: "XRP",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "ADA/USDT",
                baseAsset: "ADA",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "DOGE/USDT",
                baseAsset: "DOGE",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "AVAX/USDT",
                baseAsset: "AVAX",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "LINK/USDT",
                baseAsset: "LINK",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "DOT/USDT",
                baseAsset: "DOT",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },

            // majors vs BTC
            {
                pair: "ETH/BTC",
                baseAsset: "ETH",
                quoteAsset: "BTC",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "SOL/BTC",
                baseAsset: "SOL",
                quoteAsset: "BTC",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "BNB/BTC",
                baseAsset: "BNB",
                quoteAsset: "BTC",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "XRP/BTC",
                baseAsset: "XRP",
                quoteAsset: "BTC",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },
            {
                pair: "DOGE/BTC",
                baseAsset: "DOGE",
                quoteAsset: "BTC",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "active",
            },

            // halted — for testing circuit breaker later
            {
                pair: "SHIB/USDT",
                baseAsset: "SHIB",
                quoteAsset: "USDT",
                minOrder: 1,
                tickSize: 1,
                makerFee: 10,
                takerFee: 10,
                status: "halted",
            },
        ],
        skipDuplicates: true,
    });

    console.log("markets seeded");
}

main()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
